[package]
name = "rnet-pi-server"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[workspace.lints]
clippy.nursery = { level = "warn", priority = -1 }
clippy.pedantic = { level = "warn", priority = -1 }

[workspace]
members = [
    "openrnet_rs",
]

[dependencies]
openrnet = { path = "openrnet_rs"}