[package]
name = "rnet-pi-server"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "openrnet_rs",
]

[dependencies]
openrnet = { path = "openrnet_rs"}
bluer = {version = "0.17.4", features = ["full"]}
futures = "0.3"
tokio = { version = "1", features = ["full"] }
env_logger = "0.11"
uuid = { version = "1", features = ["v4"] }

